// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editor-box': string;
  'edui-editor': string;
}
export const cssExports: CssExports;
export default cssExports;
